<a href="https://colab.research.google.com/github/JimEverest/Deep-Learning-With-PyTorch/blob/master/1.PyTorch%20Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Fundamentals

## Matrix Basics

***Matrices Brief Introduction ***

* Basic Defination: rectangular array of numbers
* Tensors(PyTorch)
* Ndarrays(Numpy)

### 1. Creating matrix
```
torch.Tensor(arr)
```

In [0]:
import numpy as np 

In [2]:
# creating a 2*2 matrix using python

arr = [[1,2],[3,4]]
print(arr)

[[1, 2], [3, 4]]


In [8]:
#convert to numpy 

np.array(arr)


array([[1, 2],
       [3, 4]])

In [0]:
#in pytorch

import torch

In [10]:
#converting to PyTorch Tensor 

torch.Tensor(arr)

tensor([[1., 2.],
        [3., 4.]])

### 2. Creating Matrices with Default Values
```
torch.zeros((2,2))
torch.ones((2,2))
torch.rand(2,2)
```

In [11]:
#using numpy

np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [38]:
torch.zeros((2,2))

tensor([[0., 0.],
        [0., 0.]])

In [12]:
#using torch
torch.ones((2,2))

tensor([[1., 1.],
        [1., 1.]])

In [13]:
#generating random number using numpy
np.random.randn(2,2)

array([[-0.92528403, -0.27372792],
       [ 0.60405599, -0.05035653]])

In [14]:
# generating random using torch
torch.rand(2,2)

tensor([[0.4718, 0.9035],
        [0.0715, 0.7285]])

### 3. Seeds for Reproducibility
```
torch.manual_seed(0)
```

In [15]:
#numpy Seed
np.random.seed(0)
np.random.rand(2,2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [16]:
# Seed
np.random.seed(0)
np.random.rand(2,2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [17]:
# No Seed
np.random.rand(2,2) # no seed we are getting different array

array([[0.4236548 , 0.64589411],
       [0.43758721, 0.891773  ]])

In [18]:
# Torch Seed

torch.manual_seed(0)
torch.rand(2,2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [19]:
# Torch Seed

torch.manual_seed(0)
torch.rand(2,2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [20]:
# No Seed
torch.rand(2,2)

tensor([[0.3074, 0.6341],
        [0.4901, 0.8964]])

### 4. Numpy & Torch Bridge  




#### Numpy to Torch
```
torch.from_numpy(np_array)
```

In [0]:
# Numpy array
np_array = np.ones((2,2))

In [22]:
print(np_array)

[[1. 1.]
 [1. 1.]]


In [23]:
print(type(np_array))

<class 'numpy.ndarray'>


In [0]:
# Convert to Torch Tensor
torch_tensor = torch.from_numpy(np_array)

In [26]:
print(torch_tensor)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)


In [27]:
print(type(torch_tensor))

<class 'torch.Tensor'>


In [28]:
# Data Types matter in PyTorch

new_array= np.ones((2,2),dtype=np.int8)
torch.from_numpy(new_array)

tensor([[1, 1],
        [1, 1]], dtype=torch.int8)

#### The conversion supports

- double
- float
- int64,int32,uint8

In [39]:
# Data Type int64

new_array= np.ones((2,2),dtype=np.int64)
torch.from_numpy(new_array)

tensor([[1, 1],
        [1, 1]])

In [30]:
# Data Type int32
new_array= np.ones((2,2),dtype=np.int32)
torch.from_numpy(new_array)

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)

In [31]:
# Data Type uint8
new_array= np.ones((2,2),dtype=np.uint8)
torch.from_numpy(new_array)

tensor([[1, 1],
        [1, 1]], dtype=torch.uint8)

In [32]:
# Data Type float
new_array= np.ones((2,2),dtype=np.float64)
torch.from_numpy(new_array)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

In [33]:
# Data Type double
new_array= np.ones((2,2),dtype=np.double)
torch.from_numpy(new_array)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

#### Summery

These things doesn't matter much now. But later when we see error messages that require these particular tensor types , we can refer to this guide . 

| Numpy Array Type    | Torch Tensor Type     
| ------------- |:-------------:
| int64         | LongTensor
| int32         | IntegerTensor  
| uint8         | ByteTensor  
| float64       | DoubleTensor  
| float32       | FloatTensor   
| double        | DoubleTensor  

#### Torch to Numpy
```
torch_tensor.numpy()
```

In [0]:
torch_tensor = torch.ones(2,2)

In [41]:
type(torch_tensor)

torch.Tensor

In [0]:
torch_to_numpy = torch_tensor.numpy()

In [37]:
type(torch_to_numpy)

numpy.ndarray

### 5. Tensor Operations
[What's the difference between reshape and view in pytorch?](https://stackoverflow.com/questions/49643225/whats-the-difference-between-reshape-and-view-in-pytorch)
#### Resizing Tensor

```
.size()
.view() #Flatten?
```

In [43]:
a = torch.ones(2,2)
a

tensor([[1., 1.],
        [1., 1.]])

In [44]:
a.size()

torch.Size([2, 2])

In [45]:
a.view(4)   ## Flatten?

tensor([1., 1., 1., 1.])

In [46]:
a.view(4).size()

torch.Size([4])

### Element Wise Addition 
```
add
add_ (in-place operation)
```

In [47]:
a = torch.ones(2,2)
a

tensor([[1., 1.],
        [1., 1.]])

In [48]:
b = torch.ones(2,2)
b

tensor([[1., 1.],
        [1., 1.]])

In [49]:
# Element wise addition
c = a+b
c

tensor([[2., 2.],
        [2., 2.]])

In [50]:
# Element wise addition
c = torch.add(a,b)
c

tensor([[2., 2.],
        [2., 2.]])

In [51]:
# In-Place addition
#在pytorch中经常加后缀“_”来代表原地in-place operation 
# python里面的+=，*=也是in-place operation

print("Old c Tensor ")
print(c)

c.add_(a)  

print('_'*60)

print("New c Tensor ")
print(c)

Old c Tensor 
tensor([[2., 2.],
        [2., 2.]])
____________________________________________________________
New c Tensor 
tensor([[3., 3.],
        [3., 3.]])


### Element Wise Subtraction
```
.sub
.sub_
```

In [52]:
print(a)
print(b)

tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])


In [53]:
a-b

tensor([[0., 0.],
        [0., 0.]])

In [54]:
# not in-place
a.sub(b)

tensor([[0., 0.],
        [0., 0.]])

In [55]:
a

tensor([[1., 1.],
        [1., 1.]])

In [56]:
# inplace
a.sub_(b)

tensor([[0., 0.],
        [0., 0.]])

In [57]:
a

tensor([[0., 0.],
        [0., 0.]])

### Element Wise Multiplication
```
torch.mul(a,b)
a.mul_(b) 
```

In [0]:


a = torch.ones(2,2)
a

tensor([[1., 1.],
        [1., 1.]])

In [0]:
b = torch.zeros(2,2)
b

tensor([[0., 0.],
        [0., 0.]])

In [0]:
a*b

tensor([[0., 0.],
        [0., 0.]])

In [0]:
# Not in place
torch.mul(a,b)

tensor([[0., 0.],
        [0., 0.]])

In [0]:
# In-place
a.mul_(b)

tensor([[0., 0.],
        [0., 0.]])

### Element Wise Division
```
b.div(a)
b.div_(a)
```

In [0]:
a = torch.ones(2,2)
b = torch.zeros(2,2)

In [62]:
# Not In place
print(b/a)

print(b.div(a))

print(torch.div(b,a))

tensor([[0., 0.],
        [0., 0.]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[0., 0.],
        [0., 0.]])


In [0]:
# In place
b.div_(a)



tensor([[0., 0.],
        [0., 0.]])

### Tensor Mean

[Understanding dimensions in PyTorch](https://towardsdatascience.com/understanding-dimensions-in-pytorch-6edf9972d3be)
```
* 1+2+3+4+5+6+7+8+9+10 = 55
* mean = 55/10 =5.5
```

In [63]:
a = torch.Tensor([1,2,3,4,5,6,7,8,9,10])
a.size()

torch.Size([10])

In [64]:
a.mean(dim=0) #only one dimension

tensor(5.5000)

In [70]:
a = torch.Tensor([[[1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10]],[[1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10]],[[1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10]]])
a.size()

torch.Size([3, 2, 10])

In [68]:
print(a.mean(dim=1))
# print(a.mean(dim=0))


tensor([5.5000, 5.5000])
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])


In [75]:
y = torch.tensor([
  [
    [1, 2, 3],
    [4, 5, 6]
  ],
  [
    [1, 2, 3],
    [4, 5, 6]
  ],
  [
    [1, 2, 3],
    [4, 5, 6]
  ],
  [
    [1, 2, 3],
    [4, 5, 6]
  ]
])
y.shape
# torch.Size([3, 2, 3])

torch.Size([4, 2, 3])

In [78]:
print(y.sum(dim=0))
print("-"*50)
print(y.sum(dim=1))
print("-"*50)
print(y.sum(dim=2))

tensor([[ 4,  8, 12],
        [16, 20, 24]])
--------------------------------------------------
tensor([[5, 7, 9],
        [5, 7, 9],
        [5, 7, 9],
        [5, 7, 9]])
--------------------------------------------------
tensor([[ 6, 15],
        [ 6, 15],
        [ 6, 15],
        [ 6, 15]])


### Tensor Standard Deviation 

In [79]:
a = torch.Tensor([1,2,3,4,5,6,7,8,9,10])
a.std(dim=0)

tensor(3.0277)

In [81]:
a1 = np.array([1,2,3,4,5,6,7,8,9,10])
a1.std(axis=0)

2.8722813232690143