# PyTorch Fundamentals : Variables and Gradients

### 1.Variables

* A variable wraps a Tensor.
* Allows accumulation of gradients .


In [0]:
import torch
from torch.autograd import Variable

In [2]:
a = Variable(torch.ones(2,2),requires_grad=True)
a

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [3]:
# not a variable
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [0]:
# Behaves simillarly to tensors
b = Variable(torch.ones(2,2),requires_grad=True)
print(a+b)

tensor([[2., 2.],
        [2., 2.]], grad_fn=<ThAddBackward>)


In [0]:
print(torch.add(a,b))

tensor([[2., 2.],
        [2., 2.]], grad_fn=<ThAddBackward>)


In [0]:
print(a*b)

tensor([[1., 1.],
        [1., 1.]], grad_fn=<ThMulBackward>)


In [0]:
print(torch.mul(a,b))

tensor([[1., 1.],
        [1., 1.]], grad_fn=<ThMulBackward>)


In [6]:
# No requires_grad
c = Variable(torch.ones(2,2))
d = Variable(torch.ones(2,2))
print(c+d)

tensor([[2., 2.],
        [2., 2.]])


## Gradients

*** What exactly is require to use requires_grad?***
- Allows calculation of gradients w.r.t the variables.  
- Define original equation 
- Substitute equation with x values    
- Reduce the scalar output, *o* through mean 
- Calculate gradients with o.backward()   
- Then access gradients of the x variable through x.grad() 
<hr/>

*** 使用require_grad到底需要什么？
- 可以计算对于var的gradient
- 定义原始方程式
- 用x值代替方程
- 通过Reduce Mead标量输出* o *
- 用o.backward计算梯度
- 然后通过x.grad（）访问x变量的梯度




In [11]:
  # setting x = 1

x = Variable(torch.ones(2), requires_grad=True)
print(x)

tensor([1., 1.], requires_grad=True)


In [17]:
# solving a equation

y = 5 * (x +1) ** 2
print(y)

tensor([20., 20.], grad_fn=<MulBackward0>)


In [18]:
# Backward should be called only on a scalar  
o = (1/2) * torch.sum(y)
o

tensor(20., grad_fn=<MulBackward0>)

In [0]:
# backwards calculates the median
# backwards should be called only oa a scalar

o.backward()

In [20]:
# accessing the gradient
# gradient with respect to x 
x.grad

tensor([22., 22.])

In [0]:
# y = 5*(x+1)**2  (求导)
# v = x+1   #[1]
# u = v**2  #[2]
# y = 5u    #[5]

# 1*2*5 =10
# y` = 10x